project:
  type: website

website:
  title: "Module Courses"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Experimental Sociology"
        menu:
          - text: "Session 1"
            href: experimental-sociology/session1.qmd
          - text: "Session 2"
            href: experimental-sociology/session2.qmd
      - text: "Computational Social Sciences"
        menu:
          - text: "Session 1"
            href: computational-social-sciences/session1.qmd
          - text: "Session 2"
            href: computational-social-sciences/session2.qmd
      - text: "Announcements"
        href: announcements.qmd

format:
  html:
    theme: cosmo
