project:
  type: website
  output-dir: docs

website:
  title: "ES & CSS"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "General Information"
        menu:
          - text: "Anti-Discrimination Policy"
          - text: "Course Assessment"
            href: general-information/exam.qmd
          - text: "AI-Usage"
            href: general-information/ai_usage.qmd
      - text: "Experimental Sociology"
        menu:
          - text: "Session 1"
            href: experimental-sociology/session1.qmd
          - text: "Session 2"
            href: experimental-sociology/session2.qmd
      - text: "Computational Social Sciences"
        menu:
          - text: "Course Overview"
            href: "computational-social-sciences/css_overview.qmd"
          - text: "Session 1 - Kickoff"
            href: computational-social-sciences/session1.qmd
          - text: "Session 2 - SNA"
            href: computational-social-sciences/session2.qmd

format:
  html:
    theme: cosmo
