---
  title: "Experimental Sociology and Computational Social Sciences"
  subtitle: "Summer term 2025"
  date: "04/07/2025"
  date-format: long
  title-block-banner: true
  format:
    html:
      theme: cerulian
      toc: true
      toc-title: Contents
      toc-location: left
      page-layout: full
      html-math method: katex
      code-fold: false
      code-tools: false
      highlight-style: github
      eval: false
      results: hide
      embed-resources: true
      self-contained-math: true
      bibliography-style: apa
      link-citation: true
      lightbox:
        loop: true
        match: auto
---

# Announcements

::: callout-note
Some of the material (due to copyright issues) can be found at [moodle](https://moodle2.uni-leipzig.de/course/view.php?id=53760){.external target="_blank"}. The password is provided in the sessions of the first week.
:::

# Overview

Welcome to the module "Experimental Sociology and Computational Social Sciences 2025! Here you will find the two courses, most of the materials (except copyright protected papers and books used in the course) and so on.

-   **General Information**
    -   Course Assesment
    -   AI-Usage
    -   Anti-Discrimination Policy
-   [**Experimental Sociology**](experimental-sociology/es_overview.html)
    -   Lecture Contents
-   [**Computational Social Sciences**](experimental-sociology/css_overview.html)
    -   Lecture Contents

Use the navigation bar to explore course sessions and read the latest announcements.

# Format

xx

# Formal Requirements

In order to sucessfully complete the course the following requirements are to be met:

-   **Pre-examination requirement (*Prüfungsvorleistung*)**: At least 50% of the points in the 6 problem sets (*Übungsblätter*)
-   **Course assessment (*Prüfungsleistung*)**: The final grade is determined by the assessment of the term paper. (*Hausarbeit*).

# Contact Information

::::::: columns
:::: column
::: {.callout-tip collapse="false" title="Experimental Sociology - Basic Information"}
|  |  |
|:---|:---|
| Lecturer: | Dr. Sascha Grehl |
| Start: | 2025-04-09 |
| Seminar: | Thursday, 11:15 – 12:45 |
| Location: | GWZ, H2 1.15 |
| Office Hours: | by appointment, [sascha.grehl\@uni-leipzig.de](mailto:sascha.grehl@uni-leipzig.de){.email} |
:::
::::

:::: column
::: {.callout-tip collapse="false" title="Computational Social Sciences - Basic Information"}
|  |  |
|:---|:---|
| Lecturer: | MA, Leonie Steinbrinker |
| Start: | 2025-04-07 |
| Seminar: | Thuesday, 15:15 - 16:45 |
| Location: | GWZ, H2 1.15 |
| Office Hours: | by appointment, [leonie.steinbrinker\@uni-leipzig.de](mailto:leonie.steinbrinker@uni-leipzig.de){.email} |
:::
::::
:::::::
