---
title: "Course Overview"
subtitle: "Contact, Syllabus, Guidelines, KI-Usage"
date: today
date-format: short
title-block-banner: "#e7d6e6"
format:
  html:
    theme: cerulian
    toc: true
    toc-title: Contents
    toc-location: left
    page-layout: full
    html-math method: katex
    code-fold: false
    code-tools: false
    code-block-bg: true
    code-block-border-left: "#e7d6e6"
    highlight-style: atom-one
    eval: false
    results: hide
    embed-resources: true
    self-contained-math: true
    bibliography: CSS.bib
    bibliography-style: apa
    link-citation: true
    lightbox:
      loop: true
      match: auto
css: styles.css
copyright: "Copyright Leonie Steinbrinker, 2024. All Rights Reserved"
---

Welcome to the Computational Social Science (CSS) seminar! This hands-on course explores how social network analysis and geo/spatial data can enhance our understanding of society. Using R, we will learn techniques for visualizing, analyzing, and integrating these data types with existing datasets—such as survey or experimental data — to gain deeper insights into social phenomena.

::: {#custom-block}
**General Information**

|                |               |
|:---------------|---------------|
| Monday, weekly | 15:15 - 16:45 |
| GWZ, H2 1.15   | Start: 4/7/25 |
:::

Our focus will be twofold:

1.  **Social Network Analysis:** Understanding relationships and structures in network data, applying visualization techniques, and conducting empirical analyses.

2.  **Geo/Spatial Data Analysis:** Examining spatial patterns and dependencies, and leveraging location-based data for social science research.

By combining these data sources with traditional and emerging approaches—including text data (next Semester with Felix) and simulated data (this semester with Sascha) —we will explore innovative ways to study societal dynamics. Throughout the seminar, we will engage with inspiring case studies and hands-on applications to develop our own research perspectives.

This course provides both conceptual and technical foundations for working with computational methods in the social sciences, empowering participants to extend existing datasets and refine their analytical toolkit.

# About me

-   Forschungsgebiet

-   Masterarbeit über Netztwerke

-   Erreichbarkeit und Sprechstunde

# Course Goals

# Requirements

# Syllabus

+------------+--------+-----------------------------------------------------------------------------------+-------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Date       | Week   | Subject                                                                           | Content                                         | Literature and Materials                                                                                                                                                                                  |
+============+========+===================================================================================+=================================================+===========================================================================================================================================================================================================+
| 07.04.2025 | 1      | **Kick-Off**                                                                      | -   Introduction                                | -   Basic R von Veronika Batzdörfer                                                                                                                                                                       |
|            |        |                                                                                   |                                                 |                                                                                                                                                                                                           |
|            |        |                                                                                   | -   Course Setup and Structure                  | -   <https://missing.csail.mit.edu/>                                                                                                                                                                      |
|            |        |                                                                                   |                                                 |                                                                                                                                                                                                           |
|            |        |                                                                                   |     -   Background Materials                    |                                                                                                                                                                                                           |
|            |        |                                                                                   |                                                 |                                                                                                                                                                                                           |
|            |        |                                                                                   |     -   Data Overview                           |                                                                                                                                                                                                           |
|            |        |                                                                                   |                                                 |                                                                                                                                                                                                           |
|            |        |                                                                                   | -   R-Refresher                                 |                                                                                                                                                                                                           |
+------------+--------+-----------------------------------------------------------------------------------+-------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 14.04.2025 | 2      | **Networkanalysis in R**                                                          | -   Social Networks                             | [Network Data in R](https://inarwhal.github.io/NetworkAnalysisR-book/ch5-Network-Visualization-R.html#ch5-Network-Visualization-R)                                                                        |
|            |        |                                                                                   |                                                 |                                                                                                                                                                                                           |
|            |        |                                                                                   | -   Introduction to Social Networkanalysis in R | Wasserman und Faust                                                                                                                                                                                       |
|            |        |                                                                                   |                                                 |                                                                                                                                                                                                           |
|            |        |                                                                                   |     -   Representation of networks              | [Social Network Analysis 101: Ultimate Guide - Visible Network Labs](https://visiblenetworklabs.com/guides/social-network-analysis-101/)                                                                  |
|            |        |                                                                                   |                                                 |                                                                                                                                                                                                           |
|            |        |                                                                                   |     -   Network Attributes                      | -   Ausgabe 1. Übungsblatt                                                                                                                                                                                |
|            |        |                                                                                   |                                                 |                                                                                                                                                                                                           |
|            |        |                                                                                   | -   Handling missing data                       |                                                                                                                                                                                                           |
+------------+--------+-----------------------------------------------------------------------------------+-------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 21.04.2025 | 3      | **no lecture (Ostermontag)**                                                      |                                                 |                                                                                                                                                                                                           |
+------------+--------+-----------------------------------------------------------------------------------+-------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 28.04.2025 | 4      | ***Key Metrics and theoretical Insight***                                         | -   Descriptives                                |                                                                                                                                                                                                           |
|            |        |                                                                                   |                                                 |                                                                                                                                                                                                           |
|            |        |                                                                                   | -   Centrality and Assortavity                  |                                                                                                                                                                                                           |
|            |        |                                                                                   |                                                 |                                                                                                                                                                                                           |
|            |        |                                                                                   | -   Homophily                                   |                                                                                                                                                                                                           |
|            |        |                                                                                   |                                                 |                                                                                                                                                                                                           |
|            |        |                                                                                   | -   Hierarchy                                   |                                                                                                                                                                                                           |
+------------+--------+-----------------------------------------------------------------------------------+-------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 05.05.2025 | 5      | **Network Visualisation**                                                         | -   Visualisation basics                        | Zschache                                                                                                                                                                                                  |
|            |        |                                                                                   |                                                 |                                                                                                                                                                                                           |
|            |        |                                                                                   | -   Interactive visualisation                   | [Properties of real life netwirks](https://github.com/lalessan/comsocsci2024/wiki)                                                                                                                        |
+------------+--------+-----------------------------------------------------------------------------------+-------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 12.05.2025 | 6      | **Community Detection & Structural Comparison**                                   |                                                 | Aufgaben in Yans (Linköping) Skript                                                                                                                                                                       |
|            |        |                                                                                   |                                                 |                                                                                                                                                                                                           |
|            |        |                                                                                   |                                                 | Rossweil: infomap                                                                                                                                                                                         |
|            |        |                                                                                   |                                                 |                                                                                                                                                                                                           |
|            |        |                                                                                   |                                                 | PNAS - Algorithmen                                                                                                                                                                                        |
|            |        |                                                                                   |                                                 |                                                                                                                                                                                                           |
|            |        |                                                                                   |                                                 | Eigene Masterarbeit                                                                                                                                                                                       |
+------------+--------+-----------------------------------------------------------------------------------+-------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 19.05.2025 | 7      | **Statistical Models** **& Case Studies**                                         | -   ERGMs                                       | I[ntroduction to ERGMs \| Social Network Analysis for Anthropologists](https://eehh-stanford.github.io/SNA-workshop/ergm-intro.html)                                                                      |
|            |        |                                                                                   |                                                 |                                                                                                                                                                                                           |
|            |        |                                                                                   |                                                 | -   [SpiegelMining – Reverse Engineering von Spiegel-Online (33c3)](https://www.youtube.com/watch?v=-YpwsdRKt8Q)                                                                                          |
|            |        |                                                                                   |                                                 |                                                                                                                                                                                                           |
|            |        |                                                                                   |                                                 | -   [@bodaghiTheaterFakeNews2022]                                                                                                                                                                         |
|            |        |                                                                                   |                                                 |                                                                                                                                                                                                           |
|            |        |                                                                                   |                                                 | -   Internationale Flugverbindungen                                                                                                                                                                       |
|            |        |                                                                                   |                                                 |                                                                                                                                                                                                           |
|            |        |                                                                                   |                                                 | -   Verbreitung - ABM                                                                                                                                                                                     |
|            |        |                                                                                   |                                                 |                                                                                                                                                                                                           |
|            |        |                                                                                   |                                                 | -   Zune Lehmann aus Kopenhagen                                                                                                                                                                           |
+------------+--------+-----------------------------------------------------------------------------------+-------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 26.05.2025 | 8      | **Open Lab Session**                                                              | -   Q&A                                         |                                                                                                                                                                                                           |
|            |        |                                                                                   |                                                 |                                                                                                                                                                                                           |
|            |        |                                                                                   | -   Discussions                                 |                                                                                                                                                                                                           |
|            |        |                                                                                   |                                                 |                                                                                                                                                                                                           |
|            |        |                                                                                   | -   Term Paper ideas                            |                                                                                                                                                                                                           |
+------------+--------+-----------------------------------------------------------------------------------+-------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 02.06.2025 | 9      | **Geo-Data Analysis**                                                             | -   Introduction to spatial data                | [@loganMakingPlaceSpace2012]\]                                                                                                                                                                            |
|            |        |                                                                                   |                                                 |                                                                                                                                                                                                           |
|            |        |                                                                                   | -   Basics in R                                 | [@criado-perezInvisibleWomenData2019]                                                                                                                                                                     |
|            |        |                                                                                   |                                                 |                                                                                                                                                                                                           |
|            |        |                                                                                   |                                                 | -   Open Street Map Data                                                                                                                                                                                  |
|            |        |                                                                                   |                                                 |                                                                                                                                                                                                           |
|            |        |                                                                                   |                                                 | -   GIS-Daten                                                                                                                                                                                             |
|            |        |                                                                                   |                                                 |                                                                                                                                                                                                           |
|            |        |                                                                                   |                                                 | -   sf-package                                                                                                                                                                                            |
|            |        |                                                                                   |                                                 |                                                                                                                                                                                                           |
|            |        |                                                                                   |                                                 | -   [Using Spatial Data with](https://cengel.github.io/R-spatial/intro.html)                                                                                                                              |
+------------+--------+-----------------------------------------------------------------------------------+-------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 09.06.2025 | 10     | **no lecture (Pfingstmontag)**                                                    |                                                 |                                                                                                                                                                                                           |
+------------+--------+-----------------------------------------------------------------------------------+-------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 16.06.2025 | 11     | Spatial data visualisation in R                                                   | -   Visualisation                               | -   Wetterdaten auf Surveyanswers oder so                                                                                                                                                                 |
|            |        |                                                                                   |                                                 |                                                                                                                                                                                                           |
|            |        | Spatial Inference                                                                 | -   Spatial inference                           |                                                                                                                                                                                                           |
+------------+--------+-----------------------------------------------------------------------------------+-------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 23.06.2025 | 12     | Case Studies in Geodata Analysis                                                  |                                                 | [CA Bail - Using Internet search data to examine the relationship between anti-Muslim and pro -Isis sentiment in US counties](https://www.science.org/doi/10.1126/sciadv.aao5948#supplementary-materials) |
|            |        |                                                                                   |                                                 |                                                                                                                                                                                                           |
|            |        |                                                                                   |                                                 | -   Supplementary Material                                                                                                                                                                                |
|            |        |                                                                                   |                                                 |                                                                                                                                                                                                           |
|            |        |                                                                                   |                                                 | Read at home, rather discussion of method, usability, etc.                                                                                                                                                |
|            |        |                                                                                   |                                                 |                                                                                                                                                                                                           |
|            |        |                                                                                   |                                                 | Around the world - with discussion                                                                                                                                                                        |
|            |        |                                                                                   |                                                 |                                                                                                                                                                                                           |
|            |        |                                                                                   |                                                 | -   GIS-Daten Stichprobenziehung                                                                                                                                                                          |
+------------+--------+-----------------------------------------------------------------------------------+-------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 30.06.2025 | 13     | Open Science and Computational Social Science: Tools, Ethics, and Best Practices\ |                                                 | [Kurs von Christian](https://github.com/czymaraclass/CSS_WS24)                                                                                                                                            |
|            |        |                                                                                   |                                                 |                                                                                                                                                                                                           |
|            |        |                                                                                   |                                                 | \- Github,\                                                                                                                                                                                               |
|            |        |                                                                                   |                                                 | - Quarto\                                                                                                                                                                                                 |
|            |        |                                                                                   |                                                 | -                                                                                                                                                                                                         |
|            |        |                                                                                   |                                                 |                                                                                                                                                                                                           |
|            |        |                                                                                   |                                                 | OSF, etc.                                                                                                                                                                                                 |
|            |        |                                                                                   |                                                 |                                                                                                                                                                                                           |
|            |        |                                                                                   |                                                 | Best Practices, Ethische Herausforderungen, etc.                                                                                                                                                          |
|            |        |                                                                                   |                                                 |                                                                                                                                                                                                           |
|            |        |                                                                                   |                                                 | -   Diskussion                                                                                                                                                                                            |
|            |        |                                                                                   |                                                 |                                                                                                                                                                                                           |
|            |        |                                                                                   |                                                 | Raum für ganz kurze Inputvorträge, falls sich schon Gruppen gebildet haben                                                                                                                                |
|            |        |                                                                                   |                                                 |                                                                                                                                                                                                           |
|            |        |                                                                                   |                                                 | -   Open Science                                                                                                                                                                                          |
+------------+--------+-----------------------------------------------------------------------------------+-------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 07.07.2025 | 14     | **Presentations and discussion term paper**                                       |                                                 |                                                                                                                                                                                                           |
+------------+--------+-----------------------------------------------------------------------------------+-------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

: {.hover}

# Course Material

-   Felix Lennert

-   Christian Czymara

-   Veronika Batzdörfer

-   Till Hovestadt

-   Johannes Zschache